### ISSUE TITLE
Form doesn't respect colCount property and always shows one column.

### ISSUE THREAD

**Issue by Stanislav-Beresnev** [DevExpress/devextreme-react#185]
### Issue Type

bug report
### Description

The issue is related to Form

#### Steps to Reproduce

See demo and issue title
#### Demo

https://stackblitz.com/edit/devextreme-react-1ubd9e?file=index.js
### Environment Details

- devextreme version: 18.1.6-pre-18220
- devextreme-react version: 18.1.5-alpha.9
- react version: 16.4.1

**Comment by DokaRus** [comment]
Hi,
It's expected behavior. You can use the [colCountByScreen](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxForm/Configuration/colCountByScreen/) option to define `colCount` for the `xs` screen size. Another solution is to check that a [screenByWidth](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxForm/Configuration/#screenByWidth) callback doesn't return the `xs` screen size.
I've modified [your demo](https://stackblitz.com/edit/devextreme-react-d3z4vd?file=index.js) to demonstrate a possible solution.
