### ISSUE TITLE
DataGrid focusedRowEnabled={true} and customizeText provided on any column application crashes 

### ISSUE THREAD

**Issue by irfnkprc** [DevExpress/devextreme-react#329]
# Bug Report

### Steps to Reproduce:
https://codesandbox.io/s/n9x3xy624p

### Results You Received:

When focusedRowEnabled={true} on DataGrid and 
customizeText is provided to any column application crashes.

**Comment by artem-kurchenko** [comment]
Hi @irfnkprc,

The issue occurs because an arrow function is used. In this case, a new function is passed to a column each time your component is re-rendered. 
` customizeText={e => e.value.toString()}`
Define this as a stand-alone function to avoid this behavior: https://codesandbox.io/s/y04o1532x9

**Comment by irfnkprc** [comment]
@artem-kurchenko thank you very much, working fine, but i can't understand why this is happening, could you please explain little bit further, or maybe recommend some reading.

**Comment by artem-kurchenko** [comment]
You're welcome :)
The idea is described at [Handling Events](https://reactjs.org/docs/handling-events.html)
In this particular demo, the onFocusedRowChanged event handler executes the setState method. This method raises the component's "render" method again and all DataGrid props are re-evaluated. Arrow functions cause the inifinite loop in such cases.
