### ISSUE TITLE
DataGrid's rowComponent breaks 'virtual' and 'infinite' scrolling modes

### ISSUE THREAD

**Issue by gdrbyKo1** [DevExpress/devextreme-react#395]
# Bug Report

**Package versions:**

    devexteme version: 19.2.4
    devextreme-react version: 19.2.4

**Steps to reproduce:**

1. Pass any React component through DataGrid's rowComponent JSX attribute
2. Also set the DataGrid's scrolling mode to either `'virtual'` or `'infinite'`
3. Make sure there's enough data provided by dataSource for the DataGrid rows to span at least 3 (preferably more) pages
See: https://codesandbox.io/s/vibrant-elgamal-tmbky

**Current behavior:**

When a rowComponent is provided to the DataGrid component, the widget will refuse to let users browse through the whole dataset provided by the data source.
For the `'virtual'` scrolling mode, it will render 2 pages worth of data (40 rows for the default `pageSize` value of 20).
For the `'infinite'` scrolling mode, it will render only one page worth of data (20 rows for the default `pageSize` value of 20).

**Expected behavior:**

It should be possible to access all the rows provided by the data source.

**Screenshots:**

![rowcomponent-virtual-scrolling](https://user-images.githubusercontent.com/19717183/69712016-5dd3f480-1102-11ea-80c8-5c5ac655df87.png)

**Comment by LexDX** [comment]
Hi,

Note that rowComponent is incorrectly specified - it is necessary to specify the dx-row CSS class for tbody instead of tr.

Nevertheless, I reproduced the issue after changing the configuration. We will research it in the context of the following report:
[DataGrid - The "virtual" and "infinite" scrolling modes work incorrectly when rowComponent is specified](https://supportcenter.devexpress.com/ticket/details/t856595/datagrid-the-virtual-and-infinite-scrolling-modes-work-incorrectly-when-rowcomponent-is)
