### ISSUE TITLE
DataGrid's rowComponent breaks 'virtual' rowRenderingMode

### ISSUE THREAD

**Issue by gdrbyKo1** [DevExpress/devextreme-react#396]
# Bug Report

**Package versions:**

    devexteme version: 19.2.4
    devextreme-react version: 19.2.4

**Steps to reproduce:**

1. Pass any React component through DataGrid's rowComponent JSX attribute
2. Also set the DataGrid's row rendering mode to `'virtual'` and disable paging
3. Make sure the `dataSource` provides at least 11 rows
See: https://codesandbox.io/s/focused-wood-oyj2z

**Current behavior:**

When a rowComponent is provided to the DataGrid component, the widget will refuse to let users browse through the whole dataset provided by the data source.
Only the first 10 data rows are rendered.

**Expected behavior:**

It should be possible to access all the rows provided by the data source.

**Screenshots:**

![rowcompontent-virtual-rowrenderingmode](https://user-images.githubusercontent.com/19717183/69713180-60cfe480-1104-11ea-9408-827a254e4c10.png)

**Comment by LexDX** [comment]
Hi,

I see that the issue is the same as the one we are discussing in the [DataGrid - The "virtual" and "infinite" scrolling modes work incorrectly when rowComponent is specified report](https://supportcenter.devexpress.com/ticket/details/t856595/datagrid-the-virtual-and-infinite-scrolling-modes-work-incorrectly-when-rowcomponent-is) and https://github.com/DevExpress/devextreme-react/issues/395 issue. Please wait for our updates in the ticket.
