### ISSUE TITLE
Toolbar doesn't respect "itemComponent" for items with "locateInMenu": "always"

### ISSUE THREAD

**Issue by Stanislav-Beresnev** [DevExpress/devextreme-react#93]
### Issue Type

bug report

#### Steps to Reproduce

1. Init Toolbar with 
 `items ={
[
            {
              "locateInMenu": "always",
              "location": "before",
              "widget": 'button',
              "options": {
                "text": "Contacts"
              }
            }
]}` 
and 
` ItemComponent ={() => {
          return (<div>Expected</div>);
        }}`
2. Open menu in toolbar.
#### Current Behavior
`ReactToolbar` ignore `ItemComponent` and create `button` widget in menu.
#### Expected Behavior
`ReactToolbar` respect `ItemComponent` and render in `<div>Expected</div>` menu.
#### Demo

https://stackblitz.com/edit/devextreme-react-rgobqk?file=index.js
### Environment Details

devextreme 18.1.1-pre-18093
devextreme-react 18.1.1-alpha.4
react 16.3.0

**Comment by lukyanovas** [comment]
Hi,
It seems that the problem is not the React integration issue, see [this example]((https://stackblitz.com/edit/devextreme-mwaggk?file=index.js). 
DevExtreme React *Component and *Render syntax is a "mirror" of the corresponding *Template syntax in the DevExtreme API.

Please feel free to file a ticket in [the DevExpress Support Center](https://www.devexpress.com/Support/Center).
